swagger: '2.0'
info:
  version: 2.0.0
  title: SURFsharekit API
  description: |
    OpenAPI (fka Swagger) specification for the SURFsharekit API.
    # Hypermedia API
    The SURFsharekit API is designed as a *hypermedia API*. In short, this means all responses will contain hypermedia links
    to simplify the navigation between the different API calls. Each link (except `self`) is optional. When a specific link is
    not provided, this could mean the relation does not exist or the targeted endpoint is not implemented. Each client is responsible
    for checking and handling the links correctly.
    # Error responses
    Error responses are formatted in the `problem+json` media type ([RFC7807](https://tools.ietf.org/html/rfc7807)):

    ```
    {
      "code": 404,
      "title": "Resource not found"
    }
    ```
  x-logo:
    url: surfsharekitlogo.png
host: api.surfsharekit.nl
basePath:
schemes:
  - https
produces:
  - application/hal+json
  - application/problem+json
tags:
  - name: persons
    description: The persons API provides information about persons related to an educational institute.
paths:
