swagger: '2.0'
info:
  version: 2.0.0
  title: SURFsharekit API
  description: |
    OpenAPI (fka Swagger) specification for the SURFsharekit API.
    # Hypermedia API
    The SURFsharekit API is designed as a *hypermedia API*. In short, this means all responses will contain hypermedia links
    to simplify the navigation between the different API calls. Each link (except `self`) is optional. When a specific link is
    not provided, this could mean the relation does not exist or the targeted endpoint is not implemented. Each client is responsible
    for checking and handling the links correctly.
    # Error responses
    Error responses are formatted in the `problem+json` media type ([RFC7807](https://tools.ietf.org/html/rfc7807)):

    ```
    {
      "code": 404,
      "title": "Resource not found"
    }
    ```
  x-logo:
    url: logo.png
host: api.surfsharekit.nl
basePath: /v2
schemes:
  - https
produces:
  - application/hal+json
  - application/problem+json
tags:
  - name: persons
    description: The persons API provides information about persons related to an educational institute.
  - name: faculties
    description: The organizational parts of an organization.
  - name: educational departments
    description: The educational departments of an organization.
  - name: educational plans
    description: The educational plans API provides information about the plans in which the study is organized
  - name: course groups
    description: The course groups API provides informations about the groups which organizes the courses
  - name: courses
    description: The courses API provides information about the course. Updated on ad hoc-base.
  - name: course results
    description: The course result API provides the (list of) test results from a specific course attended by a student.
  - name: test results
    description: The test result API provides information about the results from the tests from different courses done by the student.
  - name: buildings
    description: The building API provides general information about buildings in use by the organization.
  - name: rooms
    description: The rooms API provides general information about rooms and specific information about the workplaces available. Updated continuously.
  - name: schedules
    description: The schedules API provides information about the planning of the courses in lessons. Updated on ad hoc-base.
  - name: news feeds
    description: The news feeds API returns news feeds aggregating one or more news items. Updated on ad hoc-base.
  - name: news items
    description: The news items API returns news items, used in the news feeds. Updated on ad hoc-base.
paths:
